### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by owldown** [veebch/walkman#1]
Newly installed on Mac with Ventura and got the error in the title:
`ModuleNotFoundError: No module named 'yaml'
`
I tried
`python3 -m pip install yaml
`
and got an error that it could not find a version that satisfies the requirement

Did some more googling and tried
`python3 -m pip pyyaml
`
after that, walkman.py was able to run. Hope this helps someone.

**Comment by veebch** [comment]
This is useful....Thanks. I'll add a requirements file...
